spec/spec_helper.rb:
  hiera_config: 'spec/fixtures/hiera.yaml'
  spec_overrides:
    - 'RSpec.configure do |c|'
    - '  c.after(:suite) do'
    - '    RSpec::Puppet::Coverage.report!'
    - '  end'
    - 'end'
